platform :ios, '10.1'

inhibit_all_warnings!

use_frameworks!

target 'GithubSelector_Example' do
    pod 'GithubSelector', :path => '../'
    pod 'SnapKit', '~> 3.2.0'
#    pod 'Presentables', '~> 0.1.3'
#    pod 'OctoKit.swift', :git => 'https://github.com/manGoweb/octokit.swift'
    pod 'KeychainSwift'
    
    target 'GithubSelector_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 1.0.0'
        pod 'Nimble', '~> 5.1.1'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end
