platform :ios, '10.3'

#inhibit_all_warnings!

use_frameworks!

target 'GithubSelector_Example' do
    pod 'GithubSelector', :path => '../'
    pod 'SnapKit', '~> 4.0.0'
    pod 'KeychainSwift'
    
    target 'GithubSelector_Tests' do
        inherit! :search_paths
        
        #pod 'Quick', '~> 1.0.0'
        #pod 'Nimble', '~> 5.1.1'
        #pod 'FBSnapshotTestCase'
        #pod 'Nimble-Snapshots'
    end
end
