platform :ios, '9.1'

inhibit_all_warnings!

use_frameworks!

target 'GithubSelector_Example' do
    pod 'GithubSelector', :path => '../'
    pod 'SnapKit'
    pod 'Presentables'
    pod 'OctoKit.swift'
    
    target 'GithubSelector_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 1.0.0'
        pod 'Nimble', '~> 5.1.1'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end
